ktor:
  deployment:
    port: 8080
#    watch:
#      - classes
#      - resources
  development: false
  application:
    modules:
      - com.example.ApplicationKt.main

jwt:
  secret: "secret"
  expected-issuer: "Auth Server"

datasource:
  url: "jdbc:postgresql://localhost:5432/employees"
  user: "postgres"
  password: "postgres"
